### ISSUE TITLE
`npm start` fails

### ISSUE THREAD

**Issue by samiheikki** [webbidevaus/webbidevaus.fi#8]
Probably failing due to missing youtube/simplecast api keys?

Full log:
```
> webbidevaus.fi@1.0.0 start /Users/samiheikki/dev/freetime/webbidevaus.fi
> npm run develop


> webbidevaus.fi@1.0.0 develop /Users/samiheikki/dev/freetime/webbidevaus.fi
> dotenv gatsby develop

success open and validate gatsby-configs — 0.123 s
success load plugins — 0.186 s
success onPreInit — 0.480 s
success delete html and css files from previous builds — 0.005 s
success initialize cache — 0.009 s
success copy gatsby files — 0.053 s
success onPreBootstrap — 0.005 s
⡀ source and transform nodes{ Error: Request failed with status code 400
    at createError (/Users/samiheikki/dev/freetime/webbidevaus.fi/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/Users/samiheikki/dev/freetime/webbidevaus.fi/node_modules/axios/lib/core/settle.js:18:12)
    at IncomingMessage.handleStreamEnd (/Users/samiheikki/dev/freetime/webbidevaus.fi/node_modules/axios/lib/adapters/http.js:201:11)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1094:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  config:
   { adapter: [Function: httpAdapter],
     transformRequest: { '0': [Function: transformRequest] },
     transformResponse: { '0': [Function: transformResponse] },
     timeout: 0,
     xsrfCookieName: 'XSRF-TOKEN',
     xsrfHeaderName: 'X-XSRF-TOKEN',
     maxContentLength: -1,
     validateStatus: [Function: validateStatus],
     headers:
      { Accept: 'application/json, text/plain, */*',
        'User-Agent': 'axios/0.18.0' },
     method: 'get',
     baseURL: 'https://www.googleapis.com/youtube/v3/',
     url:
      'https://www.googleapis.com/youtube/v3/channels?part=contentDetails&id=undefined&key=undefined',
     data: undefined },
  request:
   ClientRequest {
     _events:
      { socket: [Function],
        abort: [Function],
        aborted: [Function],
        error: [Function],
        timeout: [Function],
        prefinish: [Function: requestOnPrefinish] },
     _eventsCount: 6,
     _maxListeners: undefined,
     output: [],
     outputEncodings: [],
     outputCallbacks: [],
     outputSize: 0,
     writable: true,
     _last: true,
     chunkedEncoding: false,
     shouldKeepAlive: false,
     useChunkedEncodingByDefault: false,
     sendDate: false,
     _removedConnection: false,
     _removedContLen: false,
     _removedTE: false,
     _contentLength: 0,
     _hasBody: true,
     _trailer: '',
     finished: true,
     _headerSent: true,
     socket:
      TLSSocket {
        _tlsOptions: [Object],
        _secureEstablished: true,
        _securePending: false,
        _newSessionPending: false,
        _controlReleased: true,
        _SNICallback: null,
        servername: 'www.googleapis.com',
        alpnProtocol: false,
        authorized: true,
        authorizationError: null,
        encrypted: true,
        _events: [Object],
        _eventsCount: 8,
        connecting: false,
        _hadError: false,
        _handle: null,
        _parent: null,
        _host: 'www.googleapis.com',
        _readableState: [ReadableState],
        readable: false,
        _maxListeners: undefined,
        _writableState: [WritableState],
        writable: false,
        allowHalfOpen: false,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: undefined,
        _server: null,
        ssl: null,
        _requestCert: true,
        _rejectUnauthorized: true,
        parser: null,
        _httpMessage: [Circular],
        write: [Function: writeAfterFIN],
        [Symbol(res)]: [TLSWrap],
        [Symbol(asyncId)]: 693,
        [Symbol(lastWriteQueueSize)]: 0,
        [Symbol(timeout)]: null,
        [Symbol(kBytesRead)]: 608,
        [Symbol(kBytesWritten)]: 198,
        [Symbol(connect-options)]: [Object] },
     connection:
      TLSSocket {
        _tlsOptions: [Object],
        _secureEstablished: true,
        _securePending: false,
        _newSessionPending: false,
        _controlReleased: true,
        _SNICallback: null,
        servername: 'www.googleapis.com',
        alpnProtocol: false,
        authorized: true,
        authorizationError: null,
        encrypted: true,
        _events: [Object],
        _eventsCount: 8,
        connecting: false,
        _hadError: false,
        _handle: null,
        _parent: null,
        _host: 'www.googleapis.com',
        _readableState: [ReadableState],
        readable: false,
        _maxListeners: undefined,
        _writableState: [WritableState],
        writable: false,
        allowHalfOpen: false,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: undefined,
        _server: null,
        ssl: null,
        _requestCert: true,
        _rejectUnauthorized: true,
        parser: null,
        _httpMessage: [Circular],
        write: [Function: writeAfterFIN],
        [Symbol(res)]: [TLSWrap],
        [Symbol(asyncId)]: 693,
        [Symbol(lastWriteQueueSize)]: 0,
        [Symbol(timeout)]: null,
        [Symbol(kBytesRead)]: 608,
        [Symbol(kBytesWritten)]: 198,
        [Symbol(connect-options)]: [Object] },
     _header:
      'GET /youtube/v3/channels?part=contentDetails&id=undefined&key=undefined HTTP/1.1\r\nAccept: application/json, text/plain, */*\r\nUser-Agent: axios/0.18.0\r\nHost: www.googleapis.com\r\nConnection: close\r\n\r\n',
     _onPendingData: [Function: noopPendingOutput],
     agent:
      Agent {
        _events: [Object],
        _eventsCount: 1,
        _maxListeners: undefined,
        defaultPort: 443,
        protocol: 'https:',
        options: [Object],
        requests: {},
        sockets: [Object],
        freeSockets: {},
        keepAliveMsecs: 1000,
        keepAlive: false,
        maxSockets: Infinity,
        maxFreeSockets: 256,
        maxCachedSessions: 100,
        _sessionCache: [Object] },
     socketPath: undefined,
     timeout: undefined,
     method: 'GET',
     path:
      '/youtube/v3/channels?part=contentDetails&id=undefined&key=undefined',
     _ended: true,
     res:
      IncomingMessage {
        _readableState: [ReadableState],
        readable: false,
        _events: [Object],
        _eventsCount: 3,
        _maxListeners: undefined,
        socket: [TLSSocket],
        connection: [TLSSocket],
        httpVersionMajor: 1,
        httpVersionMinor: 1,
        httpVersion: '1.1',
        complete: true,
        headers: [Object],
        rawHeaders: [Array],
        trailers: {},
        rawTrailers: [],
        aborted: false,
        upgrade: false,
        url: '',
        method: null,
        statusCode: 400,
        statusMessage: 'Bad Request',
        client: [TLSSocket],
        _consuming: true,
        _dumped: false,
        req: [Circular],
        responseUrl:
         'https://www.googleapis.com/youtube/v3/channels?part=contentDetails&id=undefined&key=undefined',
        redirects: [] },
     aborted: undefined,
     timeoutCb: null,
     upgradeOrConnect: false,
     parser: null,
     maxHeadersCount: null,
     _redirectable:
      Writable {
        _writableState: [WritableState],
        writable: true,
        _events: [Object],
        _eventsCount: 2,
        _maxListeners: undefined,
        _options: [Object],
        _ended: true,
        _ending: true,
        _redirectCount: 0,
        _redirects: [],
        _requestBodyLength: 0,
        _requestBodyBuffers: [],
        _onNativeResponse: [Function],
        _currentRequest: [Circular],
        _currentUrl:
         'https://www.googleapis.com/youtube/v3/channels?part=contentDetails&id=undefined&key=undefined' },
     [Symbol(isCorked)]: false,
     [Symbol(outHeadersKey)]: { accept: [Array], 'user-agent': [Array], host: [Array] } },
  response:
   { status: 400,
     statusText: 'Bad Request',
     headers:
      { vary: 'X-Origin, Origin,Accept-Encoding',
        'content-type': 'application/json; charset=UTF-8',
        date: 'Wed, 24 Apr 2019 07:51:35 GMT',
        expires: 'Wed, 24 Apr 2019 07:51:35 GMT',
        'cache-control': 'private, max-age=0',
        'x-content-type-options': 'nosniff',
        'x-frame-options': 'SAMEORIGIN',
        'x-xss-protection': '1; mode=block',
        server: 'GSE',
        'alt-svc': 'quic=":443"; ma=2592000; v="46,44,43,39"',
        'accept-ranges': 'none',
        connection: 'close' },
     config:
      { adapter: [Function: httpAdapter],
        transformRequest: [Object],
        transformResponse: [Object],
        timeout: 0,
        xsrfCookieName: 'XSRF-TOKEN',
        xsrfHeaderName: 'X-XSRF-TOKEN',
        maxContentLength: -1,
        validateStatus: [Function: validateStatus],
        headers: [Object],
        method: 'get',
        baseURL: 'https://www.googleapis.com/youtube/v3/',
        url:
         'https://www.googleapis.com/youtube/v3/channels?part=contentDetails&id=undefined&key=undefined',
        data: undefined },
     request:
      ClientRequest {
        _events: [Object],
        _eventsCount: 6,
        _maxListeners: undefined,
        output: [],
        outputEncodings: [],
        outputCallbacks: [],
        outputSize: 0,
        writable: true,
        _last: true,
        chunkedEncoding: false,
        shouldKeepAlive: false,
        useChunkedEncodingByDefault: false,
        sendDate: false,
        _removedConnection: false,
        _removedContLen: false,
        _removedTE: false,
        _contentLength: 0,
        _hasBody: true,
        _trailer: '',
        finished: true,
        _headerSent: true,
        socket: [TLSSocket],
        connection: [TLSSocket],
        _header:
         'GET /youtube/v3/channels?part=contentDetails&id=undefined&key=undefined HTTP/1.1\r\nAccept: application/json, text/plain, */*\r\nUser-Agent: axios/0.18.0\r\nHost: www.googleapis.com\r\nConnection: close\r\n\r\n',
        _onPendingData: [Function: noopPendingOutput],
        agent: [Agent],
        socketPath: undefined,
        timeout: undefined,
        method: 'GET',
        path:
         '/youtube/v3/channels?part=contentDetails&id=undefined&key=undefined',
        _ended: true,
        res: [IncomingMessage],
        aborted: undefined,
        timeoutCb: null,
        upgradeOrConnect: false,
        parser: null,
        maxHeadersCount: null,
        _redirectable: [Writable],
        [Symbol(isCorked)]: false,
        [Symbol(outHeadersKey)]: [Object] },
     data: { error: [Object] } } }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! webbidevaus.fi@1.0.0 develop: `dotenv gatsby develop`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the webbidevaus.fi@1.0.0 develop script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/samiheikki/.npm/_logs/2019-04-24T07_51_35_589Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! webbidevaus.fi@1.0.0 start: `npm run develop`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the webbidevaus.fi@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/samiheikki/.npm/_logs/2019-04-24T07_51_35_615Z-debug.log
```

**Comment by rikukissa** [comment]
Damn, good point.. It's a bit tricky to get API keys for Simplecast. I created a new branch and a PR for mocking out the simplecast integration when API keys are not provided. 

You can use this branch as a base for your PR for now: https://github.com/webbidevaus/webbidevaus.fi/pull/9

Youtube API keys can be generated from [Google Developer Console](https://console.developers.google.com/apis/)

You'll need to find something that looks like this:
![image](https://user-images.githubusercontent.com/1206987/56653413-4c22fe00-6696-11e9-9486-35b49858aa3a.png)

It might open the right place from [this URL](https://console.developers.google.com/apis/library/youtube.googleapis.com)

Then enable it and generate a new API Key from Credentials (I think).

Create a `.env` file to the root of the project. It should look like this

```
YOUTUBE_CHANNEL_ID=UCNYn3Or32Kjd3uzYw_qVVLQ
YOUTUBE_API_KEY=<key you generated>
```

Hope this helps 😬 Let me know if you get stuck

**Comment by samiheikki** [comment]
That works, thanks! Might want to add that instruction to README as well.

**Comment by rikukissa** [comment]
Awesome 🤩 I'll add it as part of that PR asap

**Comment by rikukissa** [comment]
Installation instructions updated
